name: redis
version: 1.1.0
author: Luka Rahne <luka.rahne@gmail.com>
description: Redis database (https://redis.io/) client, with both simplicity and performance as primary goals.
homepage: https://github.com/ra1u/redis-dart
repository: https://github.com/ra1u/redis-dart
issue_tracker: https://github.com/ra1u/redis-dart/issues
environment:
  sdk: '>=2.0.0 <3.0.0'
